// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(MSB_Database))]
    [Migration("20240315142641_Mig5")]
    partial class Mig5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Address.AddressModel", b =>
                {
                    b.Property<Guid>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserModelId")
                        .HasColumnType("char(36)");

                    b.HasKey("AddressId");

                    b.HasIndex("UserModelId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Domain.Models.UserModel.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d3f345d-d494-4a53-af72-a079fd7b4a7e"),
                            Email = "Adam@gmail.com",
                            FirstName = "Adam",
                            LastName = "Andersson",
                            Password = "Adam123"
                        },
                        new
                        {
                            Id = new Guid("3d5dd7a8-04ac-4a99-b0ba-6ecda4addd6b"),
                            Email = "Bertil@gmail.com",
                            FirstName = "Bertil",
                            LastName = "Bengtsson",
                            Password = "Bertil123"
                        },
                        new
                        {
                            Id = new Guid("e338824e-22f8-4a83-8a80-14c1ca52630c"),
                            Email = "Cecar@gmail.com",
                            FirstName = "Cecar",
                            LastName = "Citron",
                            Password = "Cecar123"
                        },
                        new
                        {
                            Id = new Guid("237ca902-fee1-4cee-b19c-3286bb3be960"),
                            Email = "Erik@gmail.com",
                            FirstName = "Erik",
                            LastName = "Eriksson",
                            Password = "Erik123"
                        },
                        new
                        {
                            Id = new Guid("74526f85-6dcb-473e-bc71-8f70a1df29c7"),
                            Email = "Fredrik@gmail.com",
                            FirstName = "Fredrik",
                            LastName = "Fredriksson",
                            Password = "Fredrik123"
                        });
                });

            modelBuilder.Entity("Domain.Models.Address.AddressModel", b =>
                {
                    b.HasOne("Domain.Models.UserModel.UserModel", null)
                        .WithMany("Addresses")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("Domain.Models.UserModel.UserModel", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
